# Extraction

## 1. Web Scraping

In [1]:
import requests #Sending and receiving HTTP requests
from bs4 import BeautifulSoup #Parsing and navigation of HTML and XML web pages
import pandas as pd #For data manipulation and analysis

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_Indonesian_provinces_by_GDP'

In [3]:
def get_table_names(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

    # Dapatkan semua elemen tabel
    tables = soup.find_all('table')

    # Loop melalui setiap tabel dan dapatkan nama kelasnya
    table_names = []
    for table in tables:
        class_name = table.get('class')
        if class_name:
            table_names.append(class_name)

    return table_names

url = 'https://en.wikipedia.org/wiki/List_of_Indonesian_provinces_by_GDP'
table_names = get_table_names(url)

# Cetak nama kelas dari setiap tabel
for i, name in enumerate(table_names, 1):
    print(f"Table {i} Class Name: {name}")

Table 1 Class Name: ['sidebar', 'nomobile', 'nowraplinks']
Table 2 Class Name: ['wikitable', 'sortable', 'plainrowheaders']
Table 3 Class Name: ['wikitable', 'sortable']
Table 4 Class Name: ['wikitable', 'sortable']
Table 5 Class Name: ['nowraplinks', 'mw-collapsible', 'autocollapse', 'navbox-inner']
Table 6 Class Name: ['nowraplinks', 'mw-collapsible', 'autocollapse', 'navbox-inner']

In [4]:
#Send a request to the webpage
response = requests.get(url)

#Parse HTML content using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

#Find the table with class 'wikitable sortable plainrowheaders jquery-tablesorter'
table = soup.find('table', {'class': 'plainrowheaders'})

#Extract the table headers
headers = []
for th in table.find_all('th'):
  headers.append(th.text.strip())

#Extract the table headers
headers = []
for th in table.find_all('th'):
  headers.append(th.text.strip())

#Extract the table data
data = []
for tr in table.find_all('tr'):
  row_data = []
  for td in tr.find_all(['td', 'th']):
    row_data.append(td.text.strip())
  if len(row_data) > 0: #Filter baris yang tidak memiliki data
    data.append(row_data)

#Handle the case where header and data columns do not match
if len(headers) != len(data[0]):
  # Jika jumlah kolom header tidak sesuai dengan jumlah kolom data, gunakan indeks sebagai nama kolom
  headers = [str(i) for i in range(len(data[0]))]

In [5]:
#Create Pandas DataFrame for the data
gdp_prov = pd.DataFrame(data, columns = headers)

# Print the DataFrame
gdp_prov.head()

,0,1,2,3,4,5
0,Rank,Province,Region,GDP[8](in billion Rp),GDP Nominal,GDP PPP
1,(in billion $),(in billion $),None,None,None,None
2,-,Indonesia,South East Asia,"19,588,455","1,319.19","4,023.50"
3,-,Java Island,Indonesia,"10,813,999",728.27,"2,272.54"
4,-,Sumatra Island,Indonesia,"4,220,203",284.21,886.87

In [6]:
gdp_prov.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       44 non-null     object
 1   1       44 non-null     object
 2   2       43 non-null     object
 3   3       43 non-null     object
 4   4       43 non-null     object
 5   5       43 non-null     object
dtypes: object(6)
memory usage: 2.2+ KB

### Data Cleaning

In [7]:
# Membuat nama kolom sesuai dengan tabel pada web
gdp_prov.columns = ["Rank", "Province", "Region", "GDP[8](in billion Rp)", "GDP Nominal (in billion $)", "GDP PPP (in billion $)"]

# Hapus baris pertama dan kedua
gdp_prov = gdp_prov.drop([0, 1])

In [8]:
pd.set_option('display.max_rows', None)

gdp_prov

,Rank,Province,Region,GDP[8](in billion Rp),GDP Nominal (in billion $),GDP PPP (in billion $)
2,-,Indonesia,South East Asia,"19,588,455","1,319.19","4,023.50"
3,-,Java Island,Indonesia,"10,813,999",728.27,"2,272.54"
4,-,Sumatra Island,Indonesia,"4,220,203",284.21,886.87
5,1,Jakarta,Java,"3,186,470",214.59,669.63
6,2,East Java,Java,"2,730,907",183.91,573.89
7,3,West Java,Java,"2,422,782",163.16,509.14
8,-,Kalimantan,Indonesia,"1,767,053",119.00,371.34
9,4,Central Java,Java,"1,560,899",105.12,328.02
10,-,Sulawesi Island,Indonesia,"1,168,122",81.64,245.72
11,5,Riau,Sumatra,"991,589",66.78,208.38
12,6,North Sumatra,Sumatra,"955,193",64.33,200.73
13,7,East Kalimantan,Kalimantan,"921,332",62.05,193.62
14,8,Banten,Java,"747,250",50.32,157.03
15,9,South Sulawesi,Sulawesi,"605,145",40.75,124.32
16,10,South Sumatra,Sumatra,"591,603",39.84,124.32
17,-,Lesser Sunda Islands,Indonesia,"520,895",35.08,109.46
18,11,Lampung,Sumatra,"414,131",27.89,87.03
19,-,Western New Guinea,Indonesia,"353,806",23.83,74.35
20,12,Central Sulawesi,Sulawesi,"323,617",21.79,68.01
21,13,Riau Islands,Sumatra,"308,843",20.80,64.90
22,14,West Sumatra,Sumatra,"285,379",19.22,59.97
23,15,Jambi,Sumatra,"276,316",18.61,58.07
24,16,Papua,Western New Guinea,"262,516",17.68,55.17
25,17,West Kalimantan,Kalimantan,"255,797",17.23,53.76
26,18,South Kalimantan,Kalimantan,"251,256",16.92,52.80
27,19,Bali,Lesser Sunda Islands,"245,233",16.52,51.54
28,20,Aceh,Sumatra,"211,750",14.26,44.50
29,21,Central Kalimantan,Kalimantan,"199,948",13.47,42.02
30,22,Special Region of Yogyakarta,Java,"165,690",11.16,34.82
31,23,Southeast Sulawesi,Sulawesi,"158,761",10.69,33.36
32,24,North Sulawesi,Sulawesi,"157,028",10.58,33.00
33,25,West Nusa Tenggara,Lesser Sunda Islands,"156,944",10.57,32.98
34,26,North Kalimantan,Kalimantan,"138,718",9.34,29.15
35,-,Maluku Islands,Indonesia,"124,596",8.39,26.18
36,27,East Nusa Tenggara,Lesser Sunda Islands,"118,718",8.00,24.95
37,28,Bangka Belitung Islands,Sumatra,"95,285",6.42,20.02
38,29,West Papua,Western New Guinea,"91,292",6.15,19.18
39,30,Bengkulu,Sumatra,"90,112",6.07,18.94
40,31,North Maluku,Maluku Islands,"70,903",4.77,14.90
41,32,West Sulawesi,Sulawesi,"54,071",3.64,11.36
42,33,Maluku,Maluku Islands,"53,692",3.62,11.28
43,34,Gorontalo,Sulawesi,"47,574",3.20,10.00

In [9]:
#Menghapus data yang bukan merupakan data provinsi
gdp_prov = gdp_prov[~gdp_prov['Rank'].str.contains('-')]

gdp_prov

,Rank,Province,Region,GDP[8](in billion Rp),GDP Nominal (in billion $),GDP PPP (in billion $)
5,1,Jakarta,Java,"3,186,470",214.59,669.63
6,2,East Java,Java,"2,730,907",183.91,573.89
7,3,West Java,Java,"2,422,782",163.16,509.14
9,4,Central Java,Java,"1,560,899",105.12,328.02
11,5,Riau,Sumatra,"991,589",66.78,208.38
12,6,North Sumatra,Sumatra,"955,193",64.33,200.73
13,7,East Kalimantan,Kalimantan,"921,332",62.05,193.62
14,8,Banten,Java,"747,250",50.32,157.03
15,9,South Sulawesi,Sulawesi,"605,145",40.75,124.32
16,10,South Sumatra,Sumatra,"591,603",39.84,124.32
18,11,Lampung,Sumatra,"414,131",27.89,87.03
20,12,Central Sulawesi,Sulawesi,"323,617",21.79,68.01
21,13,Riau Islands,Sumatra,"308,843",20.80,64.90
22,14,West Sumatra,Sumatra,"285,379",19.22,59.97
23,15,Jambi,Sumatra,"276,316",18.61,58.07
24,16,Papua,Western New Guinea,"262,516",17.68,55.17
25,17,West Kalimantan,Kalimantan,"255,797",17.23,53.76
26,18,South Kalimantan,Kalimantan,"251,256",16.92,52.80
27,19,Bali,Lesser Sunda Islands,"245,233",16.52,51.54
28,20,Aceh,Sumatra,"211,750",14.26,44.50
29,21,Central Kalimantan,Kalimantan,"199,948",13.47,42.02
30,22,Special Region of Yogyakarta,Java,"165,690",11.16,34.82
31,23,Southeast Sulawesi,Sulawesi,"158,761",10.69,33.36
32,24,North Sulawesi,Sulawesi,"157,028",10.58,33.00
33,25,West Nusa Tenggara,Lesser Sunda Islands,"156,944",10.57,32.98
34,26,North Kalimantan,Kalimantan,"138,718",9.34,29.15
36,27,East Nusa Tenggara,Lesser Sunda Islands,"118,718",8.00,24.95
37,28,Bangka Belitung Islands,Sumatra,"95,285",6.42,20.02
38,29,West Papua,Western New Guinea,"91,292",6.15,19.18
39,30,Bengkulu,Sumatra,"90,112",6.07,18.94
40,31,North Maluku,Maluku Islands,"70,903",4.77,14.90
41,32,West Sulawesi,Sulawesi,"54,071",3.64,11.36
42,33,Maluku,Maluku Islands,"53,692",3.62,11.28
43,34,Gorontalo,Sulawesi,"47,574",3.20,10.00

In [10]:
gdp_prov.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34 entries, 5 to 43
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Rank                        34 non-null     object
 1   Province                    34 non-null     object
 2   Region                      34 non-null     object
 3   GDP[8](in billion Rp)       34 non-null     object
 4   GDP Nominal (in billion $)  34 non-null     object
 5   GDP PPP (in billion $)      34 non-null     object
dtypes: object(6)
memory usage: 1.9+ KB

In [11]:
# Melakukan rename kolom
new_column_names = {'Rank': 'rank', 'Province': 'province','Region': 'region', 'GDP[8](in billion Rp)': 'gdp_in_billion_rp',
                    'GDP Nominal (in billion $)': 'gdp_in_billion_usd', 'GDP PPP (in billion $)': 'gdp_ppp_in_billion_usd'}
gdp_prov = gdp_prov.rename(columns=new_column_names)

gdp_prov.head()

,rank,province,region,gdp_in_billion_rp,gdp_in_billion_usd,gdp_ppp_in_billion_usd
5,1,Jakarta,Java,"3,186,470",214.59,669.63
6,2,East Java,Java,"2,730,907",183.91,573.89
7,3,West Java,Java,"2,422,782",163.16,509.14
9,4,Central Java,Java,"1,560,899",105.12,328.02
11,5,Riau,Sumatra,"991,589",66.78,208.38

## 2. Application Programming Interface (API)

In [12]:
#URL Open Cage API
url = 'https://api.opencagedata.com/geocode/v1/json'

#API Key for Open Cage
api = 'c33dddca819645e7b63a683366d9afd4'

In [13]:
#Extract list of Province from DataFrame
provinces = gdp_prov['province'].to_list()

#Create a dictionary of the components data for each province
components_list = []

#Loop to each province and make request to Open Cage API
for province in provinces:

  #Create API request parameters
  params = {'q': province, 'key': api}

  #Send a request to API
  response = requests.get(url, params=params)

  #Parse the JSON response
  json_data = response.json()

  #Extract the components data from the JSON response
  components = json_data['results'][0]['components']

  #Create a dictionary of the components data for this province
  province_components = {'province': province,
                         'latitude': json_data['results'][0]['geometry']['lat'],
                         'longitude': json_data['results'][0]['geometry']['lng']}

  #Append the dictionary to a list of dictionaries
  components_list.append(province_components)

components_list

[{'province': 'Jakarta', 'latitude': -6.175247, 'longitude': 106.8270488},
 {'province': 'East Java', 'latitude': -7.6977397, 'longitude': 112.4914199},
 {'province': 'West Java', 'latitude': -6.8891904, 'longitude': 107.6404716},
 {'province': 'Central Java',
  'latitude': -7.3032412,
  'longitude': 110.0044145},
 {'province': 'Riau', 'latitude': 0.5004112, 'longitude': 101.5475811},
 {'province': 'North Sumatra', 'latitude': 2.1923519, 'longitude': 99.3812201},
 {'province': 'East Kalimantan',
  'latitude': 0.7884397,
  'longitude': 116.2419977},
 {'province': 'Banten', 'latitude': -6.4453801, 'longitude': 106.1375586},
 {'province': 'South Sulawesi',
  'latitude': -3.6446718,
  'longitude': 119.9471906},
 {'province': 'South Sumatra',
  'latitude': -3.1266842,
  'longitude': 104.0930554},
 {'province': 'Lampung', 'latitude': -4.8555039, 'longitude': 105.0272986},
 {'province': 'Central Sulawesi',
  'latitude': -1.6937786,
  'longitude': 120.8088555},
 {'province': 'Riau Islands',
  'latitude': -0.1547846,
  'longitude': 104.5803745},
 {'province': 'West Sumatra',
  'latitude': -0.5827529,
  'longitude': 100.6133379},
 {'province': 'Jambi', 'latitude': -1.6394711, 'longitude': 102.9454264},
 {'province': 'Papua', 'latitude': -2.4749149, 'longitude': 138.08485},
 {'province': 'West Kalimantan',
  'latitude': -0.1322387,
  'longitude': 111.0968901},
 {'province': 'South Kalimantan',
  'latitude': -2.9285686,
  'longitude': 115.3700718},
 {'province': 'Bali', 'latitude': -8.3304977, 'longitude': 115.0906401},
 {'province': 'Aceh', 'latitude': 4.3685491, 'longitude': 97.0253024},
 {'province': 'Central Kalimantan',
  'latitude': -1.499583,
  'longitude': 113.2903307},
 {'province': 'Special Region of Yogyakarta',
  'latitude': -7.9778384,
  'longitude': 110.3672257},
 {'province': 'Southeast Sulawesi',
  'latitude': -3.5491199,
  'longitude': 121.7279646},
 {'province': 'North Sulawesi',
  'latitude': 0.6555692,
  'longitude': 124.090151},
 {'province': 'West Nusa Tenggara',
  'latitude': -8.7892855,
  'longitude': 117.146169},
 {'province': 'North Kalimantan',
  'latitude': 3.0235817,
  'longitude': 116.2049306},
 {'province': 'East Nusa Tenggara',
  'latitude': -8.5656787,
  'longitude': 120.6978581},
 {'province': 'Bangka Belitung Islands',
  'latitude': -2.7052886,
  'longitude': 106.3585607},
 {'province': 'West Papua', 'latitude': -2.8553556, 'longitude': 133.4738171},
 {'province': 'Bengkulu', 'latitude': -3.5186763, 'longitude': 102.5359834},
 {'province': 'North Maluku', 'latitude': 0.6301215, 'longitude': 127.9720219},
 {'province': 'West Sulawesi',
  'latitude': -2.4974546,
  'longitude': 119.3918955},
 {'province': 'Maluku', 'latitude': -2.5842259, 'longitude': 127.4789451},
 {'province': 'Gorontalo', 'latitude': 0.7186174, 'longitude': 122.4555927}]

In [14]:
#Create DataFrame for components_list
components_df = pd.DataFrame(components_list)
components_df

                        province  latitude   longitude
0                        Jakarta -6.175247  106.827049
1                      East Java -7.697740  112.491420
2                      West Java -6.889190  107.640472
3                   Central Java -7.303241  110.004414
4                           Riau  0.500411  101.547581
5                  North Sumatra  2.192352   99.381220
6                East Kalimantan  0.788440  116.241998
7                         Banten -6.445380  106.137559
8                 South Sulawesi -3.644672  119.947191
9                  South Sumatra -3.126684  104.093055
10                       Lampung -4.855504  105.027299
11              Central Sulawesi -1.693779  120.808856
12                  Riau Islands -0.154785  104.580375
13                  West Sumatra -0.582753  100.613338
14                         Jambi -1.639471  102.945426
15                         Papua -2.474915  138.084850
16               West Kalimantan -0.132239  111.096890
17              South Kalimantan -2.928569  115.370072
18                          Bali -8.330498  115.090640
19                          Aceh  4.368549   97.025302
20            Central Kalimantan -1.499583  113.290331
21  Special Region of Yogyakarta -7.977838  110.367226
22            Southeast Sulawesi -3.549120  121.727965
23                North Sulawesi  0.655569  124.090151
24            West Nusa Tenggara -8.789286  117.146169
25              North Kalimantan  3.023582  116.204931
26            East Nusa Tenggara -8.565679  120.697858
27       Bangka Belitung Islands -2.705289  106.358561
28                    West Papua -2.855356  133.473817
29                      Bengkulu -3.518676  102.535983
30                  North Maluku  0.630122  127.972022
31                 West Sulawesi -2.497455  119.391896
32                        Maluku -2.584226  127.478945
33                     Gorontalo  0.718617  122.455593

# Transformation

### 1. Data Integration

In [15]:
# Merge DataFrame for Extraction
df = pd.merge(gdp_prov, components_df, on ='province')
df.head()

,rank,province,region,gdp_in_billion_rp,gdp_in_billion_usd,gdp_ppp_in_billion_usd,latitude,longitude
0,1,Jakarta,Java,"3,186,470",214.59,669.63,-6.175247,106.827049
1,2,East Java,Java,"2,730,907",183.91,573.89,-7.697740,112.491420
2,3,West Java,Java,"2,422,782",163.16,509.14,-6.889190,107.640472
3,4,Central Java,Java,"1,560,899",105.12,328.02,-7.303241,110.004414
4,5,Riau,Sumatra,"991,589",66.78,208.38,0.500411,101.547581

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34 entries, 0 to 33
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   rank                    34 non-null     object
 1   province                34 non-null     object
 2   region                  34 non-null     object
 3   gdp_in_billion_rp       34 non-null     object
 4   gdp_in_billion_usd      34 non-null     object
 5   gdp_ppp_in_billion_usd  34 non-null     object
 6   latitude                34 non-null     float64
 7   longitude               34 non-null     float64
dtypes: float64(2), object(6)
memory usage: 2.4+ KB

## 2. Data Cleaning

In [17]:
# Membersihkan nilai dari tanda koma dan mengubah tipe data ke integer
df['gdp_in_billion_rp']= df['gdp_in_billion_rp'].str.replace(',', '').astype(int)

#Change data type to integer
df[['rank', 'gdp_in_billion_rp']]= df[['rank', 'gdp_in_billion_rp']].astype(int)

#Change data type to float
df[['gdp_in_billion_usd', 'gdp_ppp_in_billion_usd']]= df[['gdp_in_billion_usd', 'gdp_ppp_in_billion_usd']].astype(float)

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 34 entries, 0 to 33
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   rank                    34 non-null     int64
 1   province                34 non-null     object
 2   region                  34 non-null     object
 3   gdp_in_billion_rp       34 non-null     int64
 4   gdp_in_billion_usd      34 non-null     float64
 5   gdp_ppp_in_billion_usd  34 non-null     float64
 6   latitude                34 non-null     float64
 7   longitude               34 non-null     float64
dtypes: float64(4), int64(2), object(2)
memory usage: 2.4+ KB

## 3. Data Enrichment

In [18]:
#Add column lat_long
df['lat_long'] = df['latitude'].astype(str) + ',' + df['longitude'].astype(str)

df.head()

,rank,province,region,gdp_in_billion_rp,gdp_in_billion_usd,gdp_ppp_in_billion_usd,latitude,longitude,lat_long
0,1,Jakarta,Java,3186470,214.59,669.63,-6.175247,106.827049,"-6.175247,106.8270488"
1,2,East Java,Java,2730907,183.91,573.89,-7.697740,112.491420,"-7.6977397,112.4914199"
2,3,West Java,Java,2422782,163.16,509.14,-6.889190,107.640472,"-6.8891904,107.6404716"
3,4,Central Java,Java,1560899,105.12,328.02,-7.303241,110.004414,"-7.3032412,110.0044145"
4,5,Riau,Sumatra,991589,66.78,208.38,0.500411,101.547581,"0.5004112,101.5475811"

# Export Data

In [19]:
df.to_csv('etl_project.csv', index=False)